name: Build and Push Exceed frontend image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      IMAGE_TAG: ${{ format('v{0}', github.run_number) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./git_update.sh -v major
