name: Build and Push Exceed frontend image to AWS ECR

on:
  push:
    branches:
      - main

permissions: 
      id-token: write
      contents: read
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      IMAGE_TAG: ${{ format('v{0}', github.run_number) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure GitHub Actions Token
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Darkk-kami/doks_agro.git

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./git_update.sh -v major
